### PR TITLE
Get Code to Assemble with A65

### PR DESCRIPTION
**Pull request by jefftranter**
Get code to assemble with A65. Added make file. Can't confirm that it generates correct code.

### CODE REVIEW

**Comment by dfnr2** [comment]
Hi Jeff, 

Thank you for this patch.

It looks like there are multiple versions of A65 floating around.  Can you provide a link to the version of A65 that you used?  Is this the version on Mark's site?

It would be good to confirm that the assembled version works before merging.  Have you tried running it?

Dave

**Comment by jefftranter** [comment]
I used A65v120w.zip from https://osi.marks-lab.com/software/tools.html
I built and and ran it on Linux.

I can confirm that the assembled binary code exactly matches the HEXDOS boot track of the image found at https://www.osiweb.org/software/hexdos/Hexdos.zip

There are more steps involved in getting the code onto a bootable disk image. I have an Ohio Scientific 600 board with 3.5" floppy disks emulating 8" disks. It looks like HEXDOS only supported 5.25" disks, so I am unable to test it. So far I have had some luck trying to convert the 5.25" image to 8", but it is not fully functional (it boots , but I cannot save files).

**Comment by dfnr2** [comment]
Great!  I will pull it in.   If you are able to build a bootable disk, it would be great if we could document it here as well.

Thanks!

Dave

**Comment by SteveHx** [comment]
On 2023-04-09 09:10 AM, Jeff Tranter wrote:
> It looks like HEXDOS only supported 5.25" disks, so I am unable to 
> test it. So far I have had some luck trying to convert the 5.25" image 
> to 8", but it is not fully functional (it boots , but I cannot save 
> files).

That is correct. At the time I wrote it (early 1980's) I had access only 
to 5.25" disks. It is very tightly optimized, and assumes a disk 
consists of N tracks of exactly 2048 bytes each. It is so tightly 
optimized for space (to fit the whole thing into one 2048 byte track), 
that I recall spending several days working to squeeze it down by one 
more byte. Not very efficient use of my time, of course, but I learned a 
heck of a lot in the process.

The one exception was that the boot track could have a few dozen excess 
bytes. Those bytes would fall during boot into the beginning of Basic's 
user program space, and thus became the home for an auto-start program, 
shortly after I saw the autoexec.bat feature on a very early IBM PC.

Steve Hendrix
HexDOS Author

**Pull request merged**
